import os
import shutil

os.system("git init")
os.system("git remote add origin https://github.com/pedrosouzacan/app-fat-carona")
os.system("git fetch origin")
os.system("git checkout main")
os.remove('db.sqlite3')
os.remove('forms.py')
os.remove('manage.py')
os.remove('models.py')
os.remove('requirements.txt')
os.remove('urls.py')
os.remove('views.py')
shutil.rmtree('accounts')
shutil.rmtree('appfat')
shutil.rmtree('rides')
shutil.rmtree('static')
shutil.rmtree('templates')
os.system('git add .')
os.system('git commit -m "Preparar merge"')
os.system('git push origin main')
os.system("git pull origin master --allow-unrelated-histories")
shutil.rmtree('None')
os.remove('READ ME.md')
shutil.rmtree('.vscode')
os.remove('db.sqlite3')
shutil.rmtree('migrations')
os.remove('merge_branch.py')
os.system('git add .')
os.system('git commit -m "Apagar arquivos desnecessários"')
os.system('git push origin main')