# Generated by Django 4.2.4 on 2023-08-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
