# Generated by Django 4.2.4 on 2023-09-13 17:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_idade_alter_profile_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cnh',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='diretorio',
            field=models.ImageField(default='/templates/static/logo_uerj1.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='placa_carro',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipos',
            field=models.CharField(choices=[('PASSAGEIRO', 'Passageiro'), ('MOTORISTA', 'Motorista')], default='Tipos.Passageiro', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
    ]
