# Generated by Django 4.2.4 on 2023-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cnh_profile_diretorio_profile_placa_carro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cnh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
