# Generated by Django 4.2.4 on 2023-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cnh_profile_diretorio_profile_placa_carro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='senha',
            field=models.CharField(default='*********', max_length=50),
        ),
    ]
