# Generated by Django 4.2.4 on 2023-09-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipos',
        ),
    ]
