# Generated by Django 4.2.4 on 2023-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diretorio',
            field=models.ImageField(default='/rides/static/img', upload_to=None),
        ),
    ]
