# Generated by Django 4.2.1 on 2023-05-21 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
