# Generated by Django 4.2 on 2023-06-16 02:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=50)),
                ('passageiro', models.CharField(max_length=50)),
                ('data_publicaçao', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('saida', models.DateTimeField(default=datetime.datetime.now)),
                ('info', models.TextField(blank=True, max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
