# Generated by Django 4.2.4 on 2023-09-19 17:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicaçao', models.DateTimeField(default=datetime.datetime.now)),
                ('data_saida', models.DateTimeField(default=datetime.datetime.now)),
                ('info', models.TextField(blank=True, max_length=200)),
                ('modalidade', models.CharField(choices=[('DEFAULT', 'Padrão'), ('UBER', 'Uber')], default='Modalidade.DEFAULT', max_length=12)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('passageiro', models.ManyToManyField(blank=True, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Rides',
        ),
    ]
