# Generated by Django 4.2.4 on 2023-08-30 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='saida',
            new_name='data_saida',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='User',
        ),
        migrations.AlterField(
            model_name='rides',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rides',
            name='passageiro',
        ),
        migrations.AddField(
            model_name='rides',
            name='passageiro',
            field=models.ManyToManyField(related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
