# Generated by Django 4.2.4 on 2023-09-13 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rides', '0004_ride_delete_rides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passageiro',
            field=models.ManyToManyField(max_length=4, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
