# Generated by Django 4.2.4 on 2023-09-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0005_alter_ride_passageiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='passageiro',
            new_name='passageiros',
        ),
    ]
